name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: print hello world!
      run: echo hello, world!
    - name: print directory!
      run: ls -al
    - name: print python version!
      run: python -V
    - name: print go version
      run: go version
